spring:
  application:
    name: MVPInfoApplication
    api:
      version: /api/1.0
  datasource:
    url: jdbc:mysql://${DB_HOST}/cockpitdb?useSSL=false
    platform: mysql
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        use-new-id-generator-mappings: false
server:
  port: 8085
