spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cockpitdb
    username: postgres
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  jira:
    username: ${JIRA_USER_NAME}
    jiraUrl: ${JIRA_HOST_URL}
    token: ${JIRA_AUTH_TOKEN}
  security:
    oauth2:
      client:
        provider:
          issuer-uri: https://pp-sso-digitalpassport.hubtotal.net/sso
        registration:
          digitalpassport:
            client-id: cockpit-dev
            client-secret: rUSzLV3CVndX5hhf3Jvm
springdoc:
  api-docs:
    path: /cockpit-api-doc
  swagger-ui:
    path: /swagger-ui/cockpit-api-doc
server:
  port: 8085