spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cockpitdb
    username: postgres
    password: password
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  jira:
    username: ${JIRA_USER_NAME}
    jiraUrl: ${JIRA_HOST_URL}
    token: ${JIRA_AUTH_TOKEN}
    urlProjects: ${JIRA_HOST_URL}/rest/api/2/project
    urlBoards: ${JIRA_HOST_URL}/rest/agile/1.0/board?maxResults=%s&startAt=%s&type=scrum
    urlSprints: ${JIRA_HOST_URL}/rest/agile/1.0/board/
    urlIssues: ${JIRA_HOST_URL}/rest/api/2/search?jql=
    urlAllUserStories: ${JIRA_HOST_URL}/rest/api/2/search?maxResults=%s&startAt=%s&jql=issuetype=Story
  digitalpass:
    isEnabled: true
    userInfoEndpoint: ${DIGITAL_PASS_USER_INFO_ENDPOINT}
springdoc:
  api-docs:
    path: /cockpit-api-doc
  swagger-ui:
    path: /swagger-ui/cockpit-api-doc
server:
  port: 8085