# Cockpit backend with JAVA Spring Boot
# Reference: https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    goals: 'clean package'

- script: |
    echo Build docker image
    docker build -t cockpitbackenddev.azurecr.io/$(imageName):$(Build.BuildNumber) .
    echo Login to docker repository
    docker login cockpitbackenddev.azurecr.io -u $(containerRegistryAdminUsername) -p $(containerRegistryAdminUserPassword)
    echo Push docker image
    docker push cockpitbackenddev.azurecr.io/$(imageName):$(Build.BuildNumber)
  displayName: 'Build and Push Image  Azure Container Registry'
