version: '3.1'
services:
#  cockpit_api:
#    build: ./
#    ports:
#      - "8080:8080"
#    depends_on:
#      - cockpit_db
  cockpit_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cockpit